{
 "title": "Maxscale Exporter",
 "tags": [ "maxscale" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "id",
    "query": "label_values(maxscale_node_status, id)"
   }
  ]
 },
 "panels": [
  { "title": "Status Maxscale / Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$id",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4.8, "x": 0, "y": 1 },
   "repeat": "id",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "maxscale_node_status{id=\"$id\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Current connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "maxscale_router_connections_current",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "maxscale_router_connections", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Maxscale",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "maxscale_up", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Master",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "maxscale_node_master == 1", "legendFormat": "{{id}}" }
   ]
  },
  { "title": "Reads / Writes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "$id read/write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "repeat": "id",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(maxscale_node_query_read{node='$id'}[2s])",
     "legendFormat": "Read"
    },
    {
     "expr": "idelta(maxscale_node_query_write{node='$id'}[2s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "$id read/write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "repeat": "id",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(maxscale_node_query_read{node='$id'}[2s])",
     "legendFormat": "Read"
    },
    {
     "expr": "idelta(maxscale_node_query_write{node='$id'}[2s])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "$id read/write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "repeat": "id",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(maxscale_node_query_read{node='$id'}[2s])",
     "legendFormat": "Read"
    },
    {
     "expr": "idelta(maxscale_node_query_write{node='$id'}[2s])",
     "legendFormat": "Write"
    }
   ]
  }
 ]
}